export const ADD_ENTRY = 'ADD_ENTRY';
export const REMOVE_ENTRY = 'REMOVE_ENTRY';
export const EDIT_ENTRY = 'EDIT_ENTRY';

export const BROWSE_ALL_ENTRIES = 'BROWSE_ALL_ENTRIES';

export const TOGGLE_LEFT_SIDEBAR = 'TOGGLE_LEFT_SIDEBAR';
