export const EDIT_ENTRY = 'EDIT_ENTRY';
export const EDIT_ENTRY_CANCEL = 'EDIT_ENTRY_CANCEL';

export const TOGGLE_LEFT_SIDEBAR = 'TOGGLE_LEFT_SIDEBAR';

export const SAVE_ENTRY_START = 'SAVE_ENTRY_START';
export const SAVE_ENTRY_SUCCESS = 'SAVE_ENTRY_SUCCESS';
export const SAVE_ENTRY_ERROR = 'SAVE_ENTRY_ERROR';
